# Generated by Django 4.2.14 on 2024-07-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectWeb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ADhistory",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="TBI",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="diet",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="disease",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="living",
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sleeping",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="smoking",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="working",
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
